stable dev
buildingamind/NewbornEmbodiedTuringTest pull request #149
Opened 2024-10-16 06:09 UTC by desaibhargav

This PR is the "stable" version of `nest-benchmarks`, in the sense that it:

1. Makes a couple of bug fixes that broke `dev` even for vanilla use-cases (no jobs start, pipeline breaks at `.run()`
2. Addresses #109, all jobs complete as expected (even with `save_checkpoints=True`. Running multiple brains with a custom encoder and `save_checkpoints` works as expected.  
3. Address #30, the python multiprocessing pool needs to be manually teared down if calling `ProcessPoolExecutor` without context (not using `with`)
4. Now allows passing either of the `["small", "medium", "large"]` to the `encoder` argument while initializing the `Brain`. The appropriate `encoder` will automatically be picked up. 
For example, 
```
brain = Brain(policy="CnnPolicy", algorithm="PPO", encoder='small')
``` 
5. Fixes a small type in the README, where `dvs` is shown as a valid argument to be passed to `Body` even after removing this behavior

2024-10-16 14:23 UTC, Zach-Attach requested changes
Looks like a great addition! A few changes need to be made first, but otherwise good work

2024-10-16 14:23 UTC, Zach-Attach commented on src/nett/brain/__init__.py
> +    encoders_dict['small'] = 'defualt'
Typo
```suggestion
    encoders_dict['small'] = 'default'
```

2024-10-16 14:23 UTC, Zach-Attach commented on src/nett/brain/builder.py
> +                encoder.__name__ = 'NatureCNN'
Minor simplification / cleanup:
```suggestion
            if encoder == 'small':
                encoder = NatureCNN
                encoder.__name__ = 'NatureCNN'
            elif encoder in encoders_dict.keys():
                encoder = getattr(encoders, encoders_dict[encoder])
```

2024-10-16 14:23 UTC, Zach-Attach commented on src/nett/nett.py
> -                    time.sleep(1)
Why are we getting rid of the synchronous flag? I would prefer an option to not have the code sit in the background

2024-10-16 14:23 UTC, Zach-Attach commented on src/nett/nett.py
> +        if mode in ["train", "full"]:
```suggestion
        if mode in ["train", "full"] or job_memory == "auto": #TODO: auto job_memory runs a train job, requiring iterations["train"] to run
```
auto memory estimation currently can only use a "train" job to estimate memory usage (which will always use more memory than a "test" job so it is the safer of the two options). Until auto memory estimation is adjusted to support accurate test job memory usage, I recommend adding this.

2024-10-16 14:23 UTC, Zach-Attach commented on src/nett/nett.py
> +
tmp path resulted in some issues and was removed in recent versions. Now uses brain_0 to store this and deletes it upon completion.
```suggestion
```

2024-10-16 14:23 UTC, Zach-Attach commented on src/nett/nett.py
> +            max_workers = 1 if len(jobs) == 1 else os.cpu_count()
Interesting. So the problem was too many workers?

2024-10-16 14:23 UTC, Zach-Attach commented on src/nett/utils/job.py
> +    return kwargs
Good catch! My bad

2024-10-19 23:50 UTC, desaibhargav commented on src/nett/brain/__init__.py
> +    encoders_dict['small'] = 'defualt'
Ah! Nice, will fix this, thanks

2024-10-19 23:51 UTC, desaibhargav commented on src/nett/nett.py
> -                    time.sleep(1)
I took it out for debugging, I'll add it again

2024-10-19 23:52 UTC, desaibhargav commented on src/nett/nett.py
> +
oh thank god, I really don't like temp paths

2024-10-19 23:53 UTC, desaibhargav commented on src/nett/nett.py
> +            max_workers = 1 if len(jobs) == 1 else os.cpu_count()
I really do not want to believe this. I'm running a test with `None`, let's see if that works

2024-10-23 02:04 UTC, desaibhargav commented
@Zach-Attach I've made the changes, I haven't added the synchro block yet, I wasn't very sure where to put it, would you want to add that after we merge to dev?

2024-11-01 19:30 UTC, desaibhargav commented on src/nett/nett.py
> -                    time.sleep(1)
Added

2024-11-01 19:30 UTC, Zach-Attach approved these changes

2024-11-01 19:30 UTC, Zach-Attach commented on src/nett/nett.py
> +    def _launch_jobs(self, jobs: list[Job], waitlist: list[Job], verbose: bool) -> dict[Future, Job]:
wait will need to be added back (this is how synchronous is passed). If you want to change the name, feel free, but this needs to stay in one way or another

2024-11-01 19:30 UTC, Zach-Attach commented on src/nett/nett.py
> +        job_sheet = self._launch_jobs(jobs, waitlist, verbose)
Synchronous needs to stay here in order for it work

2024-11-01 19:30 UTC, Zach-Attach commented on src/nett/nett.py
> -            synchronous: bool = False,
Synchronous needs to stay in order to have synchronous option work

2024-11-01 19:31 UTC, merged